/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package up.pi4.samples.javafx;

import org.junit.Test;
import static org.junit.Assert.*;

public class GraphTest {
    @Test public void testAppHasAGreeting() {
        Graph classUnderTest = new Graph();
       // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
